# Generated by Django 5.0 on 2024-01-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0002_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
