# Generated by Django 5.0 on 2024-01-07 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_profile_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileverification',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_verify', to='Profile.profile'),
        ),
    ]
