# Generated by Django 5.0 on 2024-01-07 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_alter_profileverification_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileverification',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.profile'),
        ),
    ]
