# Generated by Django 5.0 on 2024-01-13 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_alter_profileverification_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chat_wallpaper',
            field=models.ImageField(default='chat.jpg', null=True, upload_to='chat', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
