# Generated by Django 5.0 on 2024-01-17 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0008_profile_chat_wallpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='chat_wallpaper',
            field=models.ImageField(default='chat_def.jpg', null=True, upload_to='chat', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
