# Generated by Django 5.0 on 2024-01-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
