# Generated by Django 5.0 on 2024-01-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessages',
            name='pure_date',
            field=models.DateField(auto_now=True),
        ),
    ]
