# Generated by Django 5.0 on 2024-01-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0004_usermessages_pure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessages',
            name='status',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Seen', 'Seen')], default='Offline', max_length=10),
        ),
    ]
